config/routes.rb
Rails.application.routes.draw do
  root to: 'musics#index', as: 'musics_index'

  get 'musics/:idstr/:difficulty', to: 'musics#show', as: 'musics_show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/music.rb
class Music < ApplicationRecord
    validates :idstr, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
	def index
		@musics = Music.all.order(:order)
		@musictype_str = %w(Pr Fa An All)
		@difficulty_str = %w(2M 2M+ 4M 6M MM MM+)
		@bms_exist = {}
		@levels = {}
		@musics.each do |music|
			tmp_exist = []
			for i in 0..5 do
				filepath = "#{Rails.root}/app/assets/scores/#{music.idstr}#{i}.bms"
				tmp_exist[i] = File.exist?(filepath)
				unless tmp_exist[i]
					filepath = "#{Rails.root}/app/assets/scores/#{music.idstr}#{i}.notes"
					tmp_exist[i] = File.exist?(filepath)
				end
			end
			@bms_exist[music.idstr] = tmp_exist
			@levels[music.idstr] = [
				music.level_2m,
				music.level_2mp,
				music.level_4m,
				music.level_6m,
				music.level_mm,
				music.level_mmp
			]
		end
	end
	
	def show
		@music = Music.find_by(idstr: params[:idstr])
		@levels = [
			@music.level_2m,
			@music.level_2mp,
			@music.level_4m,
			@music.level_6m,
			@music.level_mm,
			@music.level_mmp
		]
		@format = "0" # 0 : bms, 1 : notes
		@score_str = ""
		@difficulty = params[:difficulty]
		@difficulty_str = %w(2M 2M+ 4M 6M MM MM+)
		filepath = "#{Rails.root}/app/assets/scores/#{@music.idstr}#{params[:difficulty]}.bms"
		unless File.exist?(filepath)
			filepath = "#{Rails.root}/app/assets/scores/#{@music.idstr}#{params[:difficulty]}.notes"
			@format = 1
		end
		File.open(filepath) do |file|
			file.each_line do |line|
				@score_str += line
			end
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
# app/helpers/application_helper.rb
module ApplicationHelper
	def default_meta_tags
	{
		site: 'ミリシタ譜面ビューア',
		title: '',
		reverse: true,
		charset: 'utf-8',
		description: 'アイドルマスター ミリオンライブ！シアターデイズ(ミリシタ)の音ゲー譜面を見やすく表示します。譜面確認にどうぞ。',
		keywords: 'ミリシタ,譜面確認,アイドルマスター,ミリオンライブ',
		canonical: request.original_url,
		separator: '|',
		icon: [
			{ href: image_url('musictypes/3.png') },
		],
		og: {
			site_name: 'ミリシタ譜面ビューア',
			title: 'ミリシタ譜面ビューア',
			description: 'アイドルマスター ミリオンライブ！シアターデイズ(ミリシタ)の音ゲー譜面を見やすく表示します。譜面確認にどうぞ。',
			type: 'website',
			url: request.original_url,
			image: image_url('musictypes/3.png'),
			locale: 'ja_JP',
		},
		twitter: {
			card: 'summary',
			site: '@MillionScore',
			creator: '@hyrorre',
		}
	}
  end
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-112158135-1"></script>
	<script>
		window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments);}
		gtag('js', new Date());

		gtag('config', 'UA-112158135-1');
	</script>
	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
	
	<%= display_meta_tags(default_meta_tags) %>
	<%= csrf_meta_tags %>
	
	<%= stylesheet_link_tag 'application', media: 'all' %>
	<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
	<script>
		(adsbygoogle = window.adsbygoogle || []).push({
			google_ad_client: "ca-pub-1154104535471881",
			enable_page_level_ads: true
		});
	</script>
</head>

<body data-controller="<%= controller_name %>" data-action="<%= action_name %>">
	<div id="pagetop"></div>
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
	<%= yield %>
	<div class="floating_div">
		<a href="#pagetop"><i class="fa fa-angle-double-up" aria-hidden="true"></i></a><br>
		<a href="#pagebottom"><i class="fa fa-angle-double-down" aria-hidden="true"></i></a>
	</div>
	<div id="pagebottom"></div>

	<script type="text/javascript" src="https://js1.nend.net/js/nendAdLoader.js"></script>
	<%= javascript_include_tag "application" %>
</body>
</html>

app/views/musics/index.html.erb
<meta name="viewport" content="width=480">
<div class="musics_index_container">
	<h1>ミリシタ譜面ビューア</h1>
	<p>
		PCなどでも動作しますが、スマホなどの縦画面端末推奨です<br>
		(Smartphone portrait is recommended.)<br>
		Android版ChromeおよびiOS版Safari最新版にて動作確認済<br>
		問題などがあれば作者のTwitter(<a target="_blank" href="https://twitter.com/hyrorre">@hyrorre</a>)、<br>
		または以下のフォームまで<br>
		<a href="https://hyrorre.com/contact/" target="_blank">Contact | HY Techs</a>
	</p>
	<div class="ad-rectangle">
		<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
		<!-- million-rectangle -->
		<ins class="adsbygoogle"
			style="display:inline-block;width:336px;height:280px"
			data-ad-client="ca-pub-1154104535471881"
			data-ad-slot="1424163788"></ins>
		<script>
		(adsbygoogle = window.adsbygoogle || []).push({});
		</script>
	</div>
	<h2>曲一覧</h2>
	<div id="itemLists">
		<details>
			<summary>検索・並び替え</summary>
			<h5>検索</h5>
			<input type="text" class="search" placeholder=""><br>

			<h5>並び替え</h5>
			<button class="sort" data-sort="order">Default</button>
			<button class="sort" data-sort="kana">Title</button>
			<button class="sort" data-sort="musictype">Type</button>
			<button class="sort" data-sort="diffnum0">2M</button>
			<button class="sort" data-sort="diffnum1">2M+</button>
			<button class="sort" data-sort="diffnum2">4M</button>
			<button class="sort" data-sort="diffnum3">6M</button>
			<button class="sort" data-sort="diffnum4">MM</button>
			<button class="sort" data-sort="added_on">Date</button>

			<h5>Other</h5>
			<label><input id="date_sw" type="checkbox"> 楽曲追加日を表示</label>
		</details>

		<ul id="musiclist" class="list">
			<% @musics.each_with_index do |music, j| %>
				<li>
					<%= image_tag("jackets/#{music.idstr}.jpg", :class => "jacket") %>
					<h3 class="title"><%= music.title %></h3>
					<%= image_tag("musictypes/#{music.musictype}.png", :class => "musictypeimage") %>
					<table class="scoretable">
						<tr>
							<% for i in 0..4 do %>
								<th><%= @difficulty_str[i] %></th>
							<% end %>
						</tr>
						<tr>
							<% for i in 0..4 do %>
								<td class="diff<%= i %> bms_exist_<%= @bms_exist[music.idstr][i] %>">
									<%= link_to @levels[music.idstr][i], musics_show_path(music.idstr, i) %>
								</td>
								<p class="diffnum diffnum<%= i %>"><%= @levels[music.idstr][i] %></p>
							<% end %>
						</tr>
					</table>
					<p class="added_on"><%= music.added_on %></p>
					<p class="kana"><%= music.kana %></p>
					<p class="order"><%= music.order %></p>
					<p class="musictype"><%= music.musictype %></p>
					<% if j % 20 == 8 %>
						<!-- <div class="ad-infeed">
							<script type="text/javascript">
								var nend_params = {"media":41408, "site":287098, "spot":838045, "type":10, "oriented":1};
							</script>
							<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
							<ins class="adsbygoogle"
								style="display:block"
								data-ad-format="fluid"
								data-ad-layout-key="-hl-4+2z-7s+4c"
								data-ad-client="ca-pub-1154104535471881"
								data-ad-slot="7155950731"></ins>
							<script>
								(adsbygoogle = window.adsbygoogle || []).push({});
							</script>
						</div> -->
					<% end %>
				</li>
			<% end %>
		</ul>
	</div>
</div>

app/views/musics/show.html.erb
<meta name="viewport" content="width=480">
<% title_diff = "#{@music.title} [#{@difficulty_str[@difficulty.to_i]}]" %>
<% set_meta_tags title: title_diff, og: {title: title_diff + " | ミリシタ譜面ビューア", image: image_url("jackets/#{@music.idstr}.jpg")} %>
<div class="musics_show_container">
	<h1>ミリシタ譜面ビューア</h1>
	<p><%= link_to "Home", musics_index_path %> > <%= title_diff %></p>
	<ul id="musiclist" class="list"><li>
		<%= image_tag("jackets/#{@music.idstr}.jpg", :class => "jacket") %>
		<h3 class="title"><%= @music.title %></h3>
		<%= image_tag("musictypes/#{@music.musictype}.png", :class => "musictypeimage") %>
		<table class="scoretable">
			<tr>
				<% for i in 0..4 do %>
					<th><%= @difficulty_str[i] %></th>
				<% end %>
			</tr>
			<tr>
				<% for i in 0..4 do %>
					<td class="diff<%= i %> bms_exist_<%= @difficulty.to_i != i %>">
						<%= link_to @levels[i], musics_show_path(@music.idstr, i) %>
					</td>
					<p class="diffnum diffnum<%= i %>"><%= @levels[i] %></p>
				<% end %>
			</tr>
		</table>
		<p class="added_on"><%= @music.added_on %></p>
	</li></ul>
	<div class="ad-rectangle">
		<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
		<!-- million-rectangle -->
		<ins class="adsbygoogle"
			style="display:inline-block;width:336px;height:280px"
			data-ad-client="ca-pub-1154104535471881"
			data-ad-slot="1424163788"></ins>
		<script>
		(adsbygoogle = window.adsbygoogle || []).push({});
		</script>
	</div>
	<details>
		<summary>設定</summary>
		<h5>
			譜面の幅
			<select name="Width" id="width_select" title="Width">
				<% for i in 5..20 do %>
					<option value="<%= i * 10 %>" class="opval<%= i * 10 %>" <%= (i == 10 ? "selected" : "") %>><%= i * 10 %>%</option>
				<% end %>
			</select>
		</h5>
		<h5>
			譜面の高さ
			<select name="Height" id="height_select" title="Height">
				<% for i in 5..20 do %>
					<option value="<%= i * 10 %>" class="opval<%= i * 10 %>" <%= (i == 10 ? "selected" : "") %>><%= i * 10 %>%</option>
				<% end %>
			</select>
		</h5>
		<p>仕様上、高さを大きくしすぎると譜面の一部が消えます。適度な値で調整してください。</p>
	</details>
	<canvas id="cv0" width="440" height="1800"></canvas>
	<canvas id="cv1" width="440" height="1800"></canvas>
	<div style="display:none;">
		<div id="difficulty"><%= @difficulty %></div>
		<div id="format"><%= @format %></div>
		<div id="score_str"><%= @score_str %></div>
	</div>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>